CREATE TABLE IF NOT EXISTS log (
    id SERIAL PRIMARY KEY,
    stage VARCHAR(20) CHECK (stage IN ('EXTRACT', 'TRANSFORM', 'LOAD_DW','LOAD_STAGGING')) NOT NULL,
    config_id INT REFERENCES config_extract(id) ON DELETE CASCADE,
    ticker VARCHAR(20),
    status VARCHAR(20) CHECK (status IN ('READY','PROCESSING','SUCCESS','FAILURE')),
    log_level VARCHAR(20) CHECK (log_level IN ('INFO','WARNING','ERROR')) DEFAULT 'INFO',
    message VARCHAR(255),
    error_message VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);